version: 2
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: circleci/node:8.7
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies
      - run:
          name: Install local deps
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Linting
          command: npm run lint
      - run:
          name: Testing
          command: npm run test
      - run:
         name: Building
         command: |
                if [ "${CIRCLE_BRANCH}" == "staging" ]; then
                     npm run build-qa
                 elif [ "${CIRCLE_BRANCH}" == "master" ]; then
                     npm run build-prod
                 else
                     npm run build-dev
                 fi
       - save_cache:
           key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
           paths:
               - dist

  deploy:
    working_directory: ~/src
    docker:
     - image: circleci/node:8.6
    steps:
     # add steps

  workflows:
    version: 2
    build_and_deploy:
      jobs:
        - build
        - deploy